"""initial_schema

Revision ID: ecff710e6dff
Revises: 
Create Date: 2026-07-13 23:56:44.823871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecff710e6dff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mibs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('docker_network_id', sa.String(length=128), nullable=True),
    sa.Column('subnet', sa.String(length=64), nullable=True),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('docker_container_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snmp_community', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('device_mibs',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('mib_id', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['mib_id'], ['mibs.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'mib_id')
    )
    op.create_table('oid_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=256), nullable=False),
    sa.Column('value_mode', sa.String(length=32), nullable=False),
    sa.Column('static_value', sa.Text(), nullable=True),
    sa.Column('random_config', sa.JSON(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('walk_seed_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'oid', name='uq_device_oid')
    )
    op.create_table('topology_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_device_id', sa.Integer(), nullable=False),
    sa.Column('src_interface', sa.String(length=128), nullable=False),
    sa.Column('dst_device_id', sa.Integer(), nullable=False),
    sa.Column('dst_interface', sa.String(length=128), nullable=False),
    sa.Column('docker_network_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dst_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['src_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topology_links')
    op.drop_table('oid_values')
    op.drop_table('device_mibs')
    op.drop_table('devices')
    op.drop_table('networks')
    op.drop_table('mibs')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
